### ISSUE TITLE
TeXdoclet can't find JDK Doclet class

### ISSUE THREAD

**Issue by vigna** [doclet/texdoclet#14]
I tried the suggested command, but I get:

```
✦ at 18:16:24 ❯ javadoc -docletpath TeXDoclet.jar  -doclet org.stfm.texdoclet.TeXDoclet     -noindex     -tree     -hyperref     -output out.tex     -title "Ranked Search Engine API"     -author "Paolo Boldi and Sebastiano Vigna"     -sourcepath src/main/java     -subpackages eu.fasten.core.search
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/javadoc/Doclet
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.loadDocletClass(Start.java:781)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.preprocess(Start.java:752)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:371)
	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:342)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
Caused by: java.lang.ClassNotFoundException: com.sun.javadoc.Doclet
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 16 more
```

**Comment by doclet** [comment]
Which java version are you using, I guess > 11? Doclet was moved to a new package in the newer java version. So maybe you can try it with an older java version till I will fix it and migrate TextDoclet to the new package?

**Comment by vigna** [comment]
Oh yes, that was the problem. Works with Java 11. I would suggest to add a big WARNING on the project web site.
